title: First site
author: Francisco Pena
email: frankbeaverpena@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This description shows up for search engine results.
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  fxpena # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
